# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialoginsertcode.ui'
#
# Created: Sat Jan  2 09:56:04 2016
#      by: pyside-uic 0.2.13 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_DialogInsertCode(object):
    def setupUi(self, DialogInsertCode):
        DialogInsertCode.setObjectName("DialogInsertCode")
        DialogInsertCode.resize(400, 300)
        DialogInsertCode.setMinimumSize(QtCore.QSize(400, 300))
        self.verticalLayout = QtGui.QVBoxLayout(DialogInsertCode)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayoutUp = QtGui.QHBoxLayout()
        self.horizontalLayoutUp.setObjectName("horizontalLayoutUp")
        self.lineEditTitle = QtGui.QLineEdit(DialogInsertCode)
        self.lineEditTitle.setObjectName("lineEditTitle")
        self.horizontalLayoutUp.addWidget(self.lineEditTitle)
        self.checkBoxFold = QtGui.QCheckBox(DialogInsertCode)
        self.checkBoxFold.setObjectName("checkBoxFold")
        self.horizontalLayoutUp.addWidget(self.checkBoxFold)
        self.checkBoxLines = QtGui.QCheckBox(DialogInsertCode)
        self.checkBoxLines.setObjectName("checkBoxLines")
        self.horizontalLayoutUp.addWidget(self.checkBoxLines)
        self.verticalLayout.addLayout(self.horizontalLayoutUp)
        self.textEdit = QtGui.QPlainTextEdit(DialogInsertCode)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayoutDown = QtGui.QHBoxLayout()
        self.horizontalLayoutDown.setObjectName("horizontalLayoutDown")
        self.comboBox = QtGui.QComboBox(DialogInsertCode)
        self.comboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayoutDown.addWidget(self.comboBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayoutDown.addItem(spacerItem)
        self.labelHint = QtGui.QLabel(DialogInsertCode)
        self.labelHint.setEnabled(False)
        self.labelHint.setText("Ctrl+Enter")
        self.labelHint.setObjectName("labelHint")
        self.horizontalLayoutDown.addWidget(self.labelHint)
        self.pushButtonOpen = QtGui.QPushButton(DialogInsertCode)
        self.pushButtonOpen.setObjectName("pushButtonOpen")
        self.horizontalLayoutDown.addWidget(self.pushButtonOpen)
        self.verticalLayout.addLayout(self.horizontalLayoutDown)

        self.retranslateUi(DialogInsertCode)
        self.comboBox.setCurrentIndex(17)
        QtCore.QMetaObject.connectSlotsByName(DialogInsertCode)
        DialogInsertCode.setTabOrder(self.lineEditTitle, self.checkBoxFold)
        DialogInsertCode.setTabOrder(self.checkBoxFold, self.checkBoxLines)
        DialogInsertCode.setTabOrder(self.checkBoxLines, self.textEdit)
        DialogInsertCode.setTabOrder(self.textEdit, self.comboBox)

    def retranslateUi(self, DialogInsertCode):
        DialogInsertCode.setWindowTitle(QtGui.QApplication.translate("DialogInsertCode", "Insert code", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditTitle.setPlaceholderText(QtGui.QApplication.translate("DialogInsertCode", "title", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxFold.setText(QtGui.QApplication.translate("DialogInsertCode", "&Fold", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxLines.setText(QtGui.QApplication.translate("DialogInsertCode", "&Lines", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("DialogInsertCode", "applescript", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("DialogInsertCode", "actionscript3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("DialogInsertCode", "bash", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("DialogInsertCode", "coldfusion", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(4, QtGui.QApplication.translate("DialogInsertCode", "cpp", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(5, QtGui.QApplication.translate("DialogInsertCode", "c#", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(6, QtGui.QApplication.translate("DialogInsertCode", "css", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(7, QtGui.QApplication.translate("DialogInsertCode", "delphi", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(8, QtGui.QApplication.translate("DialogInsertCode", "diff", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(9, QtGui.QApplication.translate("DialogInsertCode", "erlang", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(10, QtGui.QApplication.translate("DialogInsertCode", "groovy", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(11, QtGui.QApplication.translate("DialogInsertCode", "java", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(12, QtGui.QApplication.translate("DialogInsertCode", "javafx", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(13, QtGui.QApplication.translate("DialogInsertCode", "javascript", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(14, QtGui.QApplication.translate("DialogInsertCode", "perl", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(15, QtGui.QApplication.translate("DialogInsertCode", "php", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(16, QtGui.QApplication.translate("DialogInsertCode", "plain", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(17, QtGui.QApplication.translate("DialogInsertCode", "python", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(18, QtGui.QApplication.translate("DialogInsertCode", "ruby", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(19, QtGui.QApplication.translate("DialogInsertCode", "sass", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(20, QtGui.QApplication.translate("DialogInsertCode", "scala", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(21, QtGui.QApplication.translate("DialogInsertCode", "sql", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(22, QtGui.QApplication.translate("DialogInsertCode", "vb", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(23, QtGui.QApplication.translate("DialogInsertCode", "xml", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOpen.setText(QtGui.QApplication.translate("DialogInsertCode", "&Open", None, QtGui.QApplication.UnicodeUTF8))

